# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'saaraUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_saaraUi(object):
    def setupUi(self, saraUi):
        saraUi.setObjectName("saraUi")
        saraUi.resize(1137, 721)
        self.centralwidget = QtWidgets.QWidget(saraUi)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 1141, 721))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("{Your image location}\\background_img.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(910, 150, 93, 28))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 178, 102, 255), stop:0.55 rgba(235, 148, 61, 255), stop:0.98 rgba(0, 0, 0, 255), stop:1 rgba(0, 0, 0, 0));\n"
"background-color: rgb(201, 229, 255);")
        self.pushButton.setCheckable(False)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(910, 210, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("background-color: rgb(253, 0, 0);")
        self.pushButton_2.setCheckable(False)
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 270, 291, 221))
        self.label_3.setAutoFillBackground(False)
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("{Your gif location}\\middle_loading.gif"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 10, 441, 231))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("{Your gif location}\\top_loading.gif"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(670, 10, 221, 71))
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser.setStyleSheet("background:transparent;\n"
        "border-radius:none;\n"
        "color:white;\n"
        "font-style:bold;\n"
        "font-size:30px;")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.textBrowser_2.setStyleSheet("background:transparent;\n"
        "border-radius:none;\n"
        "color:white;\n"
        "font-style:bold;\n"
        "font-size:30px;")
        self.textBrowser_2.setGeometry(QtCore.QRect(910, 10, 221, 71))
        saraUi.setCentralWidget(self.centralwidget)

        self.retranslateUi(saraUi)
        QtCore.QMetaObject.connectSlotsByName(saraUi)

    def retranslateUi(self, saraUi):
        _translate = QtCore.QCoreApplication.translate
        saraUi.setWindowTitle(_translate("saraUi", "MainWindow"))
        self.pushButton.setText(_translate("saraUi", "Run"))
        self.pushButton_2.setText(_translate("saraUi", "Exit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    saraUi = QtWidgets.QMainWindow()
    ui = Ui_saraUi()
    ui.setupUi(saraUi)
    saraUi.show()
    sys.exit(app.exec_())
